import jsPDFImport from "jspdf";
import autoTableImport from "jspdf-autotable";

// Bundlers hand back the constructor directly; Node's ESM interop hands back the namespace. Resolve
// once so this module also runs outside the browser (server-side rendering, tests).
const jsPDF: typeof jsPDFImport = (jsPDFImport as any)?.default ?? jsPDFImport;
const autoTable: typeof autoTableImport = (autoTableImport as any)?.default ?? autoTableImport;

const BRAND: [number, number, number] = [113, 5, 239]; // #7105ef

export type InvoiceLike = {
  number: string; client: string; amount: number; currency?: string;
  status: string; date?: string; dueDate?: string; services?: string;
};

// ── Professional invoice PDF (built-in fallback) ──
// Builds the document without deciding what to do with it, so the exact same PDF can be either
// downloaded or previewed inline. Used whenever no custom layout has been designed.
function buildInvoicePDF(inv: InvoiceLike) {
  const doc = new jsPDF();
  const cur = inv.currency || "SAR";
  const w = doc.internal.pageSize.getWidth();

  doc.setFillColor(...BRAND);
  doc.rect(0, 0, w, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold"); doc.setFontSize(18);
  doc.text("STIMES PRO", 14, 18);
  doc.setFont("helvetica", "normal"); doc.setFontSize(10);
  doc.text("PRO & Compliance Services", 14, 24);
  doc.setFont("helvetica", "bold"); doc.setFontSize(22);
  doc.text("INVOICE", w - 14, 18, { align: "right" });

  doc.setTextColor(40, 40, 40);
  doc.setFont("helvetica", "bold"); doc.setFontSize(11);
  doc.text(inv.number, w - 14, 40, { align: "right" });
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(110, 110, 110);
  if (inv.date) doc.text(`Issued: ${inv.date}`, w - 14, 46, { align: "right" });
  if (inv.dueDate) doc.text(`Due: ${inv.dueDate}`, w - 14, 51, { align: "right" });
  doc.text(`Status: ${inv.status.toUpperCase()}`, w - 14, 56, { align: "right" });

  doc.setTextColor(150, 150, 150); doc.setFontSize(8);
  doc.text("BILL TO", 14, 42);
  doc.setTextColor(40, 40, 40); doc.setFont("helvetica", "bold"); doc.setFontSize(12);
  doc.text(inv.client, 14, 49);

  autoTable(doc, {
    startY: 66,
    head: [["Description", "Amount"]],
    body: [[inv.services || "Professional services", `${cur} ${inv.amount.toLocaleString()}`]],
    headStyles: { fillColor: BRAND, halign: "left" },
    columnStyles: { 1: { halign: "right", cellWidth: 45 } },
    styles: { fontSize: 10, cellPadding: 4 },
    theme: "striped",
  });

  const y = (doc as any).lastAutoTable.finalY + 10;
  doc.setDrawColor(230, 230, 230); doc.line(w - 90, y, w - 14, y);
  doc.setFont("helvetica", "bold"); doc.setFontSize(13); doc.setTextColor(...BRAND);
  doc.text("Total", w - 90, y + 9);
  doc.text(`${cur} ${inv.amount.toLocaleString()}`, w - 14, y + 9, { align: "right" });

  doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(150, 150, 150);
  doc.text("Thank you for your business. Generated by STIMES PRO.", 14, doc.internal.pageSize.getHeight() - 12);

  return doc;
}

// ─────────────────────────────────────────────────────────────
// SECTION-BASED PRINT LAYOUT ENGINE
// A layout is the document's real sections (Billed By, Items, Totals…). Each section can be shown or
// hidden, and within it you tick which fields print — no template tokens. The same renderer drives
// the designer preview and the real download, so what you design is what prints.
// ─────────────────────────────────────────────────────────────
export type PrintField = { key: string; label: string; show: boolean };
export type PrintSectionId = "header" | "meta" | "billedBy" | "billedTo" | "items" | "totals" | "terms" | "notes" | "signature" | "footer";
export type PrintSection = { id: PrintSectionId; show: boolean; title?: string; fields?: PrintField[]; columns?: PrintField[] };
export type PrintLayoutDef = {
  id?: string; name: string; target: string;
  sections: PrintSection[];
  // Layout-level content the admin types once (own business details, terms, footer) — as opposed to
  // per-document data, which arrives in `data`.
  settings?: Record<string, any>;
};

const ones = ["", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"];
const tens = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"];
function words(n: number): string {
  if (!isFinite(n) || n < 0) return "";
  if (n < 20) return ones[n];
  if (n < 100) return (tens[Math.floor(n / 10)] + (n % 10 ? "-" + ones[n % 10] : "")).trim();
  if (n < 1000) return (ones[Math.floor(n / 100)] + " hundred" + (n % 100 ? " " + words(n % 100) : "")).trim();
  const units: [number, string][] = [[1e9, "billion"], [1e6, "million"], [1e3, "thousand"]];
  for (const [v, name] of units) {
    if (n >= v) return (words(Math.floor(n / v)) + " " + name + (n % v ? " " + words(n % v) : "")).trim();
  }
  return String(n);
}
export const amountInWords = (n: number, cur = "SAR") => {
  const whole = Math.floor(Math.abs(n));
  const s = words(whole) || "zero";
  return `${cur} ${s.charAt(0).toUpperCase() + s.slice(1)} only`;
};

const hexToRgb = (hex?: string): [number, number, number] => {
  const m = /^#?([0-9a-f]{6})$/i.exec(String(hex ?? "").trim());
  if (!m) return BRAND;
  const n = parseInt(m[1], 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
};
const on = (sec: PrintSection | undefined, key: string) => !!sec?.fields?.find(f => f.key === key)?.show;
const labelOf = (sec: PrintSection | undefined, key: string, dflt = "") => sec?.fields?.find(f => f.key === key)?.label ?? dflt;

export function renderSectionsPDF(layout: PrintLayoutDef, data: Record<string, any>) {
  const st = layout.settings ?? {};
  const doc = new jsPDF();
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 14;
  const accent = hexToRgb(st.accent);
  const sec = (id: PrintSectionId) => layout.sections?.find(s => s.id === id && s.show);
  const val = (k: string) => { const v = data[k]; return v == null ? "" : String(v); };
  let y = M;

  // ── Header band ──
  const h = sec("header");
  if (h) {
    const bh = Number(st.headerHeight) || 28;
    doc.setFillColor(...accent); doc.rect(0, 0, W, bh, "F");
    doc.setTextColor(255, 255, 255);
    if (on(h, "orgName")) { doc.setFont("helvetica", "bold"); doc.setFontSize(18); doc.text(String(st.orgName || "STIMES PRO"), M, bh - 10); }
    if (on(h, "tagline")) { doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.text(String(st.tagline || ""), M, bh - 4); }
    if (on(h, "docTitle")) { doc.setFont("helvetica", "bold"); doc.setFontSize(22); doc.text(String(h.title || "INVOICE"), W - M, bh - 10, { align: "right" }); }
    y = bh + 12;
  }

  // ── Meta (number / dates / status) — right column ──
  const meta = sec("meta");
  let metaBottom = y;
  if (meta) {
    let my = y;
    (meta.fields ?? []).filter(f => f.show).forEach(f => {
      doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(120, 120, 120);
      doc.text(`${f.label}:`, W - M - 42, my, { align: "right" });
      doc.setFont("helvetica", "bold"); doc.setTextColor(40, 40, 40);
      doc.text(val(f.key), W - M, my, { align: "right" });
      my += 5.5;
    });
    metaBottom = my;
  }

  // ── Billed By / Billed To ──
  const by = sec("billedBy"), to = sec("billedTo");
  const partyBlock = (s: PrintSection | undefined, x: number, source: "settings" | "data") => {
    if (!s) return y;
    let py = y;
    doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(150, 150, 150);
    doc.text(String(s.title || "").toUpperCase(), x, py); py += 6;
    let first = true;
    (s.fields ?? []).filter(f => f.show).forEach(f => {
      const v = source === "settings" ? String(st[f.key] ?? "") : val(f.key);
      if (!v) return;
      const head = first; first = false;
      doc.setFont("helvetica", head ? "bold" : "normal");
      doc.setFontSize(head ? 12 : 9);
      doc.setTextColor(head ? 40 : 110, head ? 40 : 110, head ? 40 : 110);
      doc.splitTextToSize(v, 76).forEach((ln: string) => { doc.text(ln, x, py); py += head ? 6 : 4.6; });
    });
    return py;
  };
  const yl = partyBlock(by, M, "settings");
  const yr = partyBlock(to, W / 2 + 4, "data");
  y = Math.max(yl, yr, metaBottom) + 6;

  // ── Items table (only ticked columns) ──
  const items = sec("items");
  if (items) {
    const cols = (items.columns ?? []).filter(c => c.show);
    if (cols.length) {
      const rows: any[] = Array.isArray(data.items) && data.items.length ? data.items : [data];
      autoTable(doc, {
        startY: y,
        head: [cols.map(c => c.label)],
        body: rows.map(r => cols.map(c => { const v = (r as any)[c.key] ?? data[c.key]; return v == null ? "" : String(v); })),
        headStyles: { fillColor: accent, halign: "left" },
        columnStyles: Object.fromEntries(cols.map((_c, i) => [i, { halign: i === 0 ? "left" : "right" }])) as any,
        styles: { fontSize: 10, cellPadding: 4 },
        theme: (st.tableTheme as any) || "striped",
        margin: { left: M, right: M },
      });
      y = (doc as any).lastAutoTable.finalY + 8;
    }
  }

  // ── Totals ──
  const tot = sec("totals");
  if (tot) {
    const amt = Number(data.amountNum ?? 0);
    const vatRate = Number(st.vatRate ?? 0);
    const vat = amt * (vatRate / 100);
    const cur = String(data.currency || "SAR");
    const money = (n: number) => `${cur} ${n.toLocaleString(undefined, { maximumFractionDigits: 2 })}`;
    const lines: [string, string, boolean][] = [
      [labelOf(tot, "subtotal", "Subtotal"), money(amt), on(tot, "subtotal")],
      [`${labelOf(tot, "vat", "VAT")} (${vatRate}%)`, money(vat), on(tot, "vat")],
      [labelOf(tot, "total", "Total"), money(on(tot, "vat") ? amt + vat : amt), on(tot, "total")],
    ];
    const shown = lines.filter(l => l[2]);
    if (shown.length) {
      doc.setDrawColor(230, 230, 230); doc.line(W - 90, y, W - M, y); y += 7;
      shown.forEach(([lb, v], i) => {
        const last = i === shown.length - 1;
        doc.setFont("helvetica", last ? "bold" : "normal"); doc.setFontSize(last ? 13 : 10);
        if (last) doc.setTextColor(...accent); else doc.setTextColor(90, 90, 90);
        doc.text(lb, W - 90, y); doc.text(v, W - M, y, { align: "right" });
        y += last ? 9 : 6;
      });
    }
    if (on(tot, "totalWords")) {
      doc.setFont("helvetica", "italic"); doc.setFontSize(8); doc.setTextColor(120, 120, 120);
      doc.text(amountInWords(on(tot, "vat") ? amt + vat : amt, String(data.currency || "SAR")), W - M, y, { align: "right" }); y += 7;
    }
  }

  // ── Terms / Notes ──
  for (const id of ["terms", "notes"] as PrintSectionId[]) {
    const s = sec(id);
    if (!s) continue;
    const body = String(st[id === "terms" ? "termsText" : "notesText"] ?? "");
    if (!body) continue;
    y += 4;
    doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(40, 40, 40);
    doc.text(String(s.title || (id === "terms" ? "Terms & Conditions" : "Notes")), M, y); y += 5;
    doc.setFont("helvetica", "normal"); doc.setFontSize(8.5); doc.setTextColor(110, 110, 110);
    doc.splitTextToSize(body, W - M * 2).forEach((ln: string) => { doc.text(ln, M, y); y += 4.4; });
  }

  // ── Signature ──
  const sig = sec("signature");
  if (sig) {
    const sy = Math.min(y + 16, H - 34);
    doc.setDrawColor(180, 180, 180); doc.line(W - M - 55, sy, W - M, sy);
    doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(120, 120, 120);
    doc.text(String(sig.title || "Authorised Signatory"), W - M, sy + 5, { align: "right" });
  }

  // ── Footer ──
  if (sec("footer")) {
    doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(150, 150, 150);
    doc.text(String(st.footerText || ""), M, H - 12);
  }
  return doc;
}

// The default invoice design as sections — the starting point for a new layout and a faithful
// reproduction of the built-in PDF.
export const DEFAULT_INVOICE_SECTIONS: PrintSection[] = [
  { id: "header", show: true, title: "INVOICE", fields: [
    { key: "orgName", label: "Business name", show: true },
    { key: "tagline", label: "Tagline", show: true },
    { key: "docTitle", label: "Document title", show: true },
  ] },
  { id: "meta", show: true, fields: [
    { key: "number", label: "Invoice No", show: true },
    { key: "date", label: "Issued", show: true },
    { key: "dueDate", label: "Due", show: true },
    { key: "status", label: "Status", show: true },
  ] },
  { id: "billedBy", show: true, title: "Billed By", fields: [
    { key: "orgName", label: "Business name", show: true },
    { key: "orgAddress", label: "Address", show: true },
    { key: "orgEmail", label: "Email", show: false },
    { key: "orgPhone", label: "Phone", show: false },
    { key: "orgVat", label: "VAT / CR number", show: false },
  ] },
  { id: "billedTo", show: true, title: "Billed To", fields: [
    { key: "client", label: "Client name", show: true },
    { key: "clientCity", label: "City", show: false },
    { key: "clientEmail", label: "Email", show: false },
    { key: "clientPhone", label: "Phone", show: false },
    { key: "clientCr", label: "CR number", show: false },
  ] },
  { id: "items", show: true, title: "Items", columns: [
    { key: "services", label: "Description", show: true },
    { key: "qty", label: "Qty", show: false },
    { key: "rate", label: "Rate", show: false },
    { key: "amount", label: "Amount", show: true },
  ] },
  { id: "totals", show: true, fields: [
    { key: "subtotal", label: "Subtotal", show: false },
    { key: "vat", label: "VAT", show: false },
    { key: "total", label: "Total", show: true },
    { key: "totalWords", label: "Total in words", show: false },
  ] },
  { id: "terms", show: false, title: "Terms & Conditions", fields: [] },
  { id: "notes", show: false, title: "Notes", fields: [] },
  { id: "signature", show: false, title: "Authorised Signatory", fields: [] },
  { id: "footer", show: true, fields: [] },
];

export const DEFAULT_INVOICE_SETTINGS: Record<string, any> = {
  accent: "#7105ef",
  orgName: "STIMES PRO",
  tagline: "PRO & Compliance Services",
  orgAddress: "Riyadh, Saudi Arabia",
  orgEmail: "",
  orgPhone: "",
  orgVat: "",
  vatRate: 15,
  termsText: "Payment due within 30 days of the invoice date.",
  notesText: "",
  footerText: "Thank you for your business. Generated by STIMES PRO.",
};

// Flatten an invoice into the field namespace the sections tick against.
export const invoiceFields = (inv: InvoiceLike & Record<string, any>) => {
  const cur = inv.currency || "SAR";
  const n = Number(inv.amount) || 0;
  return {
    ...inv,
    currency: cur,
    amountNum: n,
    amount: `${cur} ${n.toLocaleString()}`,
    rate: `${cur} ${n.toLocaleString()}`,
    qty: "1",
    status: String(inv.status || "").toUpperCase(),
  };
};

// ─────────────────────────────────────────────────────────────
// FREE-FORM ELEMENT ENGINE
// Place any field anywhere on the page. Each element carries its own position/size in millimetres
// (A4 = 210×297mm, which is jsPDF's native unit), so the designer canvas and the PDF share one
// coordinate space — what you position is exactly where it prints.
// ─────────────────────────────────────────────────────────────
export const PAGE_W = 210, PAGE_H = 297;
export type PrintElKind = "field" | "text" | "table" | "box" | "line";
export type PrintEl = {
  id: string;
  kind: PrintElKind;
  field?: string;          // data key — the dynamic bit
  text?: string;           // static text
  label?: string;          // small caption drawn above the value
  x: number; y: number; w: number; h?: number;   // mm
  size?: number; bold?: boolean; align?: "left" | "center" | "right"; color?: string;
  fill?: string;           // box only
  columns?: { key: string; label: string; align?: string }[]; // table only
};
export type ElementLayoutDef = { id?: string; name: string; target: string; elements: PrintEl[]; settings?: Record<string, any> };

export const isElementLayout = (l?: any): boolean =>
  !!l && Array.isArray(l.elements) && l.elements.some((e: any) => e && typeof e.x === "number" && typeof e.y === "number" && typeof e.kind === "string");

// Resolve the namespace an element's `field` binds to: the layout's own business details, overlaid
// with this document's data, plus money figures computed from the layout's VAT rate.
export function elementData(layout: ElementLayoutDef, data: Record<string, any>) {
  const st = layout.settings ?? {};
  const amt = Number(data.amountNum ?? 0);
  const vatRate = Number(st.vatRate ?? 0);
  const vat = amt * (vatRate / 100);
  const cur = String(data.currency || "SAR");
  const money = (n: number) => `${cur} ${n.toLocaleString(undefined, { maximumFractionDigits: 2 })}`;
  return {
    ...st, ...data,
    subtotal: money(amt),
    vat: money(vat),
    total: money(amt + vat),
    totalWords: amountInWords(amt + vat, cur),
  } as Record<string, any>;
}

export function renderElementsPDF(layout: ElementLayoutDef, raw: Record<string, any>) {
  const doc = new jsPDF(); // a4, millimetres
  const st = layout.settings ?? {};
  const data = elementData(layout, raw);
  const accent = hexToRgb(st.accent);
  const setColor = (hex?: string) => { const [r, g, b] = hexToRgb(hex ?? "#282828"); doc.setTextColor(r, g, b); };
  const anchorX = (el: PrintEl) => el.align === "center" ? el.x + el.w / 2 : el.align === "right" ? el.x + el.w : el.x;

  for (const el of [...(layout.elements ?? [])].sort((a, b) => (a.kind === "box" ? -1 : 0) - (b.kind === "box" ? -1 : 0))) {
    switch (el.kind) {
      case "box": {
        const [r, g, b] = el.fill === "accent" ? accent : hexToRgb(el.fill ?? "#eeeeee");
        doc.setFillColor(r, g, b);
        doc.rect(el.x, el.y, el.w, el.h ?? 10, "F");
        break;
      }
      case "line":
        doc.setDrawColor(...hexToRgb(el.color ?? "#c8c8c8"));
        doc.line(el.x, el.y, el.x + el.w, el.y);
        break;
      case "table": {
        const cols = el.columns ?? [];
        if (!cols.length) break;
        const rows: any[] = Array.isArray(data.items) && data.items.length ? data.items : [data];
        autoTable(doc, {
          startY: el.y,
          head: [cols.map(c => c.label)],
          body: rows.map(r => cols.map(c => { const v = (r as any)[c.key] ?? data[c.key]; return v == null ? "" : String(v); })),
          headStyles: { fillColor: accent, halign: "left" },
          columnStyles: Object.fromEntries(cols.map((c, i) => [i, { halign: (c.align as any) || (i === 0 ? "left" : "right") }])) as any,
          styles: { fontSize: el.size ?? 10, cellPadding: 3 },
          theme: (st.tableTheme as any) || "striped",
          margin: { left: el.x, right: PAGE_W - el.x - el.w },
          tableWidth: el.w,
        });
        break;
      }
      default: {
        // field | text
        const raw = el.kind === "field" ? data[el.field ?? ""] : el.text;
        const value = raw == null ? "" : String(raw);
        let y = el.y;
        if (el.label) {
          doc.setFont("helvetica", "normal"); doc.setFontSize(7); doc.setTextColor(150, 150, 150);
          doc.text(el.label.toUpperCase(), anchorX(el), y + 2.5, { align: el.align ?? "left" });
          y += 5;
        }
        if (!value) break;
        const size = el.size ?? 10;
        doc.setFont("helvetica", el.bold ? "bold" : "normal");
        doc.setFontSize(size);
        setColor(el.color === "accent" ? undefined : el.color);
        if (el.color === "accent") doc.setTextColor(...accent);
        const lines = doc.splitTextToSize(value, Math.max(el.w, 4));
        doc.text(lines, anchorX(el), y + size * 0.36, { align: el.align ?? "left" });
      }
    }
  }
  return doc;
}

// Every field the designer can drop onto an invoice page.
export const INVOICE_FIELD_CATALOG: { group: string; items: { key: string; label: string }[] }[] = [
  { group: "Invoice", items: [
    { key: "number", label: "Invoice number" }, { key: "date", label: "Issue date" },
    { key: "dueDate", label: "Due date" }, { key: "status", label: "Status" },
    { key: "services", label: "Services / description" },
  ] },
  { group: "Client", items: [
    { key: "client", label: "Client name" }, { key: "clientCity", label: "Client city" },
    { key: "clientEmail", label: "Client email" }, { key: "clientPhone", label: "Client phone" },
    { key: "clientCr", label: "Client CR number" },
  ] },
  { group: "Money", items: [
    { key: "amount", label: "Amount" }, { key: "subtotal", label: "Subtotal" },
    { key: "vat", label: "VAT" }, { key: "total", label: "Total" },
    { key: "totalWords", label: "Total in words" }, { key: "currency", label: "Currency" },
  ] },
  { group: "Your business", items: [
    { key: "orgName", label: "Business name" }, { key: "tagline", label: "Tagline" },
    { key: "orgAddress", label: "Address" }, { key: "orgEmail", label: "Email" },
    { key: "orgPhone", label: "Phone" }, { key: "orgVat", label: "VAT / CR number" },
  ] },
];

// A standard, modern invoice, expressed as positioned elements. Restrained: one thin accent rule at
// the crown, a large quiet wordmark, generous whitespace, the total as the single loud moment.
// This is what a new layout starts from — every element is draggable and removable.
export const DEFAULT_INVOICE_ELEMENTS: PrintEl[] = [
  // crown
  { id: "m1", kind: "box", x: 0, y: 0, w: 210, h: 3, fill: "accent" },
  // masthead
  { id: "m2", kind: "field", field: "orgName", x: 16, y: 17, w: 95, size: 17, bold: true, color: "#1a1a1a" },
  { id: "m3", kind: "field", field: "tagline", x: 16, y: 25, w: 95, size: 8.5, color: "#8a8a8a" },
  { id: "m4", kind: "text", text: "INVOICE", x: 104, y: 14, w: 90, size: 30, bold: true, align: "right", color: "accent" },
  { id: "m5", kind: "field", field: "number", x: 104, y: 29, w: 90, size: 10, align: "right", color: "#8a8a8a" },
  { id: "m6", kind: "line", x: 16, y: 40, w: 178, color: "#ececec" },
  // parties + dates
  { id: "m7", kind: "field", field: "client", label: "Billed to", x: 16, y: 48, w: 85, size: 12.5, bold: true, color: "#1a1a1a" },
  { id: "m8", kind: "field", field: "clientEmail", x: 16, y: 60, w: 85, size: 8.5, color: "#8a8a8a" },
  { id: "m9", kind: "field", field: "clientCity", x: 16, y: 65, w: 85, size: 8.5, color: "#8a8a8a" },
  { id: "m10", kind: "field", field: "date", label: "Issue date", x: 118, y: 48, w: 36, size: 9.5, color: "#3a3a3a" },
  { id: "m11", kind: "field", field: "dueDate", label: "Due date", x: 158, y: 48, w: 36, size: 9.5, color: "#3a3a3a" },
  { id: "m12", kind: "field", field: "status", label: "Status", x: 158, y: 62, w: 36, size: 9.5, bold: true, color: "accent" },
  // line items
  { id: "m13", kind: "table", x: 16, y: 82, w: 178, size: 9.5, columns: [
    { key: "services", label: "Description", align: "left" },
    { key: "qty", label: "Qty", align: "right" },
    { key: "rate", label: "Rate", align: "right" },
    { key: "amount", label: "Amount", align: "right" },
  ] },
  // totals — the one loud moment
  { id: "m14", kind: "text", text: "Subtotal", x: 118, y: 112, w: 36, size: 9, color: "#8a8a8a" },
  { id: "m15", kind: "field", field: "subtotal", x: 154, y: 112, w: 40, size: 9, align: "right", color: "#3a3a3a" },
  { id: "m16", kind: "text", text: "VAT", x: 118, y: 119, w: 36, size: 9, color: "#8a8a8a" },
  { id: "m17", kind: "field", field: "vat", x: 154, y: 119, w: 40, size: 9, align: "right", color: "#3a3a3a" },
  { id: "m18", kind: "line", x: 118, y: 126, w: 76, color: "#ececec" },
  { id: "m19", kind: "text", text: "TOTAL", x: 118, y: 131, w: 40, size: 14, bold: true, color: "accent" },
  { id: "m20", kind: "field", field: "total", x: 144, y: 131, w: 50, size: 14, bold: true, align: "right", color: "accent" },
  { id: "m21", kind: "field", field: "totalWords", x: 104, y: 141, w: 90, size: 7.5, align: "right", color: "#a8a8a8" },
  // terms
  { id: "m22", kind: "text", text: "TERMS & CONDITIONS", x: 16, y: 168, w: 90, size: 7.5, bold: true, color: "#8a8a8a" },
  { id: "m23", kind: "field", field: "termsText", x: 16, y: 174, w: 115, size: 8.5, color: "#6b6b6b" },
  // footer
  { id: "m24", kind: "line", x: 16, y: 276, w: 178, color: "#ececec" },
  { id: "m25", kind: "field", field: "footerText", x: 16, y: 281, w: 178, size: 7.5, color: "#a8a8a8" },
];

// Is this actually a section layout? Guards against a stored layout in an older/unknown shape, which
// would otherwise render as a blank page. Anything unrecognised falls back to the built-in design.
export const isSectionLayout = (l?: PrintLayoutDef | null): boolean =>
  !!l && Array.isArray(l.sections) && l.sections.some(s => s && typeof (s as any).id === "string" && typeof (s as any).show === "boolean");

// `inv` may carry extra client details (clientEmail/clientCity/clientPhone/clientCr) that the Billed To
// section can tick — the caller merges them in from the Client record.
// `layout` optional → falls back to the built-in builder so printing never breaks.
// Pick the engine that matches the stored layout's shape; anything unrecognised (or absent) prints
// the built-in design, so a bad layout can never produce a blank invoice.
function invoiceDoc(inv: InvoiceLike & Record<string, any>, layout?: any) {
  const d = invoiceFields(inv);
  if (isElementLayout(layout)) return renderElementsPDF(layout, d);
  if (isSectionLayout(layout)) return renderSectionsPDF(layout, d);
  return buildInvoicePDF(inv);
}

export function invoicePDF(inv: InvoiceLike & Record<string, any>, layout?: any) {
  invoiceDoc(inv, layout).save(`${inv.number}.pdf`);
}

// The same PDF as an object URL, for inline preview in an <iframe>.
// The caller owns the URL and must URL.revokeObjectURL() it when done.
export function invoicePDFUrl(inv: InvoiceLike & Record<string, any>, layout?: any): string {
  return URL.createObjectURL(invoiceDoc(inv, layout).output("blob"));
}

// Preview a free-form layout against sample data (the designer's "Preview PDF").
export function elementPreviewUrl(layout: ElementLayoutDef, data: Record<string, any>): string {
  return URL.createObjectURL(renderElementsPDF(layout, data).output("blob"));
}

// Preview any layout against sample data (the designer's "Preview PDF").
export function layoutPreviewUrl(layout: PrintLayoutDef, data: Record<string, any>): string {
  return URL.createObjectURL(renderSectionsPDF(layout, data).output("blob"));
}

// ── Generic table report PDF (compliance, clients, tasks, audit, reports…) ──
export function tableReportPDF(title: string, columns: string[], rows: (string | number)[][], filename: string) {
  const doc = new jsPDF(columns.length > 6 ? "landscape" : "portrait");
  const w = doc.internal.pageSize.getWidth();

  doc.setFillColor(...BRAND); doc.rect(0, 0, w, 22, "F");
  doc.setTextColor(255, 255, 255); doc.setFont("helvetica", "bold"); doc.setFontSize(14);
  doc.text("STIMES PRO", 14, 14);
  doc.setFont("helvetica", "normal"); doc.setFontSize(11);
  doc.text(title, w - 14, 14, { align: "right" });

  autoTable(doc, {
    startY: 30,
    head: [columns],
    body: rows.map(r => r.map(c => String(c ?? ""))),
    headStyles: { fillColor: BRAND },
    styles: { fontSize: 8, cellPadding: 2.5 },
    theme: "striped",
    didDrawPage: () => {
      doc.setFontSize(7); doc.setTextColor(160, 160, 160);
      doc.text(`${rows.length} records · generated ${title}`, 14, doc.internal.pageSize.getHeight() - 8);
    },
  });

  doc.save(filename);
}
